ARDUINO_DIR  = /usr/share/arduino
ARDMK_DIR    = /home/reinhard/dev/Arduino-Makefile/arduino-mk
ARDMK_PATH   = /home/reinhard/dev/Arduino-Makefile/bin
AVR_TOOLS_DIR = /usr
BOARD_TAG    = uno
MONITOR_PORT = /dev/ttyACM3
ARDUINO_LIBS = Wire TimerOne PinChangeInt Servo Streaming

EXTRA_FLAGS = -fno-use-cxa-atexit

include /home/reinhard/dev/Arduino-Makefile/arduino-mk/Arduino.mk
